syntax = "proto3";

package VMPQ;

service VMPQService {
    rpc InitTable (InitTableRequest) returns (InitTableResponse) {}
    rpc UpdateVarList (UpdateVarListRequest) returns (UpdateVarListResponse) {}
    rpc UpdateBatchVarList (UpdateBatchVarListRequest) returns (UpdateBatchVarListResponse) {}
    rpc UpdateTableVar (UpdateTableVarRequest) returns (UpdateTableVarResponse) {}
    rpc UpdateBatchTable (UpdateBatchTableRequest) returns (UpdateBatchTableResponse) {}
}

message InitTableRequest {
    string tableID = 1;
    uint32 windowSize = 2;
    uint32 numBucketSize = 3;
}

message InitTableResponse {
    bytes res = 1;
}

message UpdateVarListRequest {
    string varListID = 1;
    uint32 idx = 2;
    bytes val = 3;
}

message UpdateVarListResponse {
    bytes res = 1;
}

message UpdateBatchVarListRequest {
    string varListID = 1;
    repeated UpdateVarListRequest list = 2;
}

message UpdateBatchVarListResponse {
    bytes res = 1;
}

message UpdateTableVarRequest {
    string tableID = 1;
    repeated bytes val = 2;
}

message UpdateTableVarResponse {
    bytes res = 1;
}

message UpdateBatchTableRequest {
    string tableID = 1;
    repeated UpdateTableVarRequest update = 2;
}

message UpdateBatchTableResponse {
    bytes res = 1;
}
